Update build-source-gem script to support v2.
rails/ruby-coffee-script pull request #23
Opened 2017-10-22 05:54 UTC by gobijan

As far as I understood the coffee-script integration for rails depends on coffee-script-source gem which is built via this script.
I modified the script to use version 2 of the CoffeeScript compiler instead of version 1.
Also I make sure that if no version is set I get the latest tag for the build.

2017-10-23 19:01 UTC, rafaelfranca requested changes

2017-10-23 19:01 UTC, rafaelfranca commented on script/build-source-gem
> +mv docs/v2/browser-compiler/coffeescript.js lib/coffee_script/coffee-script.js
This  also needs to keep supporting the version 1.

2017-10-24 16:07 UTC, merged

2018-03-20 12:31 UTC, Argorate commented
@gobijan can you explain how to use it and specify V2 in rails app ? (who using "gem 'coffee-rails'" only, by default when create new rails app and not "ruby-coffee-script"). What we have to added to gem file?

2018-05-25 06:31 UTC, littlstonee commented
@Argorate After investigation,  I made coffeescript2 worked with sprockets together, hope this answer helps .

1. Install latest coffee-script.
2. Add COFFEESCRIPT_SOURCE_PATH to your operation system's variables.
3. Set COFFEESCRIPT_SOURCE_PATH value to your coffeescript.js path.
**Please make sure you use a standalone file,** you can get it from [https://coffeescript.org/v2/browser-compiler/coffeescript.js](https://coffeescript.org/v2/browser-compiler/coffeescript.js).

Everything done, enjoy!
FYI [https://github.com/rails/ruby-coffee-script#installation](https://github.com/rails/ruby-coffee-script#installation)
![1](https://user-images.githubusercontent.com/10240090/40529617-507365a0-6028-11e8-8626-6df4b98ca91b.jpg)